services:

  postgres:
    image: postgres:16

    environment:
      POSTGRES_USER: raguser
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: ragchatbot

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  ollama:
    image: ollama/ollama

    ports:
      - "11434:11434"

    volumes:
      - ollama_data:/root/.ollama

  backend:
    build: ./backend

    ports:
      - "8000:8000"

    depends_on:
      - postgres
      - ollama

    environment:
      DATABASE_URL: postgresql://raguser:password123@postgres:5432/ragchatbot
      OLLAMA_URL: http://ollama:11434

    volumes:
      - ./backend:/app
      - chroma_data:/app/chroma_data

  frontend:
    build: ./frontend

    ports:
      - "5173:5173"

    depends_on:
      - backend

    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  postgres_data:
  ollama_data:
  chroma_data: